Link to main page after successful registration
snikket-im/snikket-web-portal pull request #96
Opened 2021-08-27 14:57 UTC by Zash

Someone who registers via the web might also be interested in proceeding to the web portal. Perhaps it's just me as a developer and/or admin.

Suggestions for proper wording, or better solutions would be appreciated.

2021-08-28 09:43 UTC, horazont commented on snikket_web/templates/invite_success.html
> +	<p><a href="/">{% trans %}Check out the web portal something something?{% endtrans %}</a></p>
Use `href="{{ url_for('main.login') }}"` to go to the login page directly (and without relying on magic paths :))

I'm also not quite happy with the wording ;). 

How about integrating this with the previous sentence:

`You can now safely close this page or proceed to the <a href="...">web login</a>.`

Though that might cause people to believe that they can chat from there…

2021-08-28 10:54 UTC, mwild1 commented on snikket_web/templates/invite_success.html
> +	<p><a href="/">{% trans %}Check out the web portal something something?{% endtrans %}</a></p>
This is related to #95 - this is indeed a weird dead-end page for users currently. A link to the login would be an improvement indeed.

How about:

> You may close this page, or log in to the web portal to **manage your account**.

2021-08-28 12:49 UTC, horazont commented on snikket_web/templates/invite_success.html
> +	<p><a href="/">{% trans %}Check out the web portal something something?{% endtrans %}</a></p>
:+1:

2021-08-28 16:14 UTC, Zash commented on snikket_web/templates/invite_success.html
> +	<p><a href="/">{% trans %}Check out the web portal something something?{% endtrans %}</a></p>
Thanks, will incorporate feedback and drop the draft status if there's nothing else.

2021-08-28 21:15 UTC, Zash commented
@horazont pointed me to #16 which would help here as well.

2021-08-29 07:01 UTC, horazont requested changes

2021-08-29 07:01 UTC, horazont commented on snikket_web/templates/invite_success.html
> +	<p>{% trans login_url=url_for('main.login') %}You can now safely close this page, or log in to the web portal to <a href="{{ login_url }}">manage your account</a>{% endtrans %}</p>
Missing trailing period.

2021-08-29 13:23 UTC, Zash commented on snikket_web/templates/invite_success.html
> +	<p>{% trans login_url=url_for('main.login') %}You can now safely close this page, or log in to the web portal to <a href="{{ login_url }}">manage your account</a>{% endtrans %}</p>
Fixed.

2021-08-30 05:45 UTC, horazont approved these changes

2021-08-30 13:47 UTC, merged